import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "@/components/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <ClerkProvider afterSignInUrl="/dashboard" afterSignUpUrl="/dashboard">
        <html lang="en" className="light">
          <body
            className={cn(
              "grainy inter.className min-h-screen font-sans antialiased",
              inter.className
            )}
          >
            <Navbar />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </Providers>
  );
}
